version: "3.9"

services:
  # 1. FastAPI 앱
  fastapi:
    image: ghcr.io/${REPO_USER}/nawsol-server:latest
    container_name: nawsol-server
    ports:
      - "33333:33333"  # 호스트 33333 -> 컨테이너 33333
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - backend_net

  # 2. MySQL
  mysql:
    image: mysql:8.1
    container_name: nawsol_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net

  # 3. Redis
  redis:
    image: redis:8.2
    container_name: nawsol_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_net

# 볼륨 정의
volumes:
  mysql_data:
  redis_data:

# 네트워크 정의
networks:
  backend_net:
    driver: bridge
